onboarding = false

[ui]
show_agent_labels_on_pane_borders = true

[ui.toast]
delivery = "herdr"

[theme]
name = "nord"
auto_switch = false

[keys]
prefix = "alt+space"
goto = "prefix+g"

new_tab = "prefix+shift+t"
close_tab = "prefix+shift+x"
rename_tab = "prefix+shift+r"
next_tab = "alt+right"
previous_tab = "alt+left"
focus_pane_left = "prefix+h"

new_workspace = "prefix+shift+w"
next_workspace = "ctrl+alt+down"
previous_workspace = "ctrl+alt+up"

navigate_pane_down = "ctrl+j"
split_horizontal = "prefix+minus"
split_vertical = "prefix+|"

